In [1]:
import numpy as np
import pandas as pd

train_df = pd.read_csv('train_V2.csv')
test_df = pd.read_csv('test_V2.csv')

In [2]:
train_df.head()

,Id,groupId,matchId,assists,boosts,damageDealt,DBNOs,headshotKills,heals,killPlace,...,revives,rideDistance,roadKills,swimDistance,teamKills,vehicleDestroys,walkDistance,weaponsAcquired,winPoints,winPlacePerc
0,7f96b2f878858a,4d4b580de459be,a10357fd1a4a91,0,0,0.00,0,0,0,60,...,0,0.0000,0,0.00,0,0,244.80,1,1466,0.4444
1,eef90569b9d03c,684d5656442f9e,aeb375fc57110c,0,0,91.47,0,0,0,57,...,0,0.0045,0,11.04,0,0,1434.00,5,0,0.6400
2,1eaf90ac73de72,6a4a42c3245a74,110163d8bb94ae,1,0,68.00,0,0,0,47,...,0,0.0000,0,0.00,0,0,161.80,2,0,0.7755
3,4616d365dd2853,a930a9c79cd721,f1f1f4ef412d7e,0,0,32.90,0,0,0,75,...,0,0.0000,0,0.00,0,0,202.70,3,0,0.1667
4,315c96c26c9aac,de04010b3458dd,6dc8ff871e21e6,0,0,100.00,0,0,0,45,...,0,0.0000,0,0.00,0,0,49.75,2,0,0.1875

In [3]:
test_df.head()

,Id,groupId,matchId,assists,boosts,damageDealt,DBNOs,headshotKills,heals,killPlace,...,rankPoints,revives,rideDistance,roadKills,swimDistance,teamKills,vehicleDestroys,walkDistance,weaponsAcquired,winPoints
0,9329eb41e215eb,676b23c24e70d6,45b576ab7daa7f,0,0,51.46,0,0,0,73,...,1500,0,0.0,0,0.0,0,0,588.0,1,0
1,639bd0dcd7bda8,430933124148dd,42a9a0b906c928,0,4,179.10,0,0,2,11,...,1503,2,4669.0,0,0.0,0,0,2017.0,6,0
2,63d5c8ef8dfe91,0b45f5db20ba99,87e7e4477a048e,1,0,23.40,0,0,4,49,...,1565,0,0.0,0,0.0,0,0,787.8,4,0
3,cf5b81422591d1,b7497dbdc77f4a,1b9a94f1af67f1,0,0,65.52,0,0,0,54,...,1465,0,0.0,0,0.0,0,0,1812.0,3,0
4,ee6a295187ba21,6604ce20a1d230,40754a93016066,0,4,330.20,1,2,1,7,...,1480,1,0.0,0,0.0,0,0,2963.0,4,0

In [4]:
train_n = len(train_df)
all_df = pd.concat([train_df,test_df], ignore_index=True ,sort=False)

In [5]:
all_df.tail()

,Id,groupId,matchId,assists,boosts,damageDealt,DBNOs,headshotKills,heals,killPlace,...,revives,rideDistance,roadKills,swimDistance,teamKills,vehicleDestroys,walkDistance,weaponsAcquired,winPoints,winPlacePerc
6381135,a316c3a13887d5,80e82180c90951,f276da5fd73536,1,2,381.00,3,0,7,4,...,1,0.0,0,0.000,0,0,1799.00,5,1526,NaN
6381136,5312146b27d875,147264a127c56e,fb77cbfe094a6b,0,0,0.00,0,0,0,64,...,0,0.0,0,0.000,0,0,1195.00,3,1496,NaN
6381137,fc8818b5b32ad3,7bbb4779ebedd5,efb74d5f6e9779,0,0,91.96,0,0,3,24,...,0,0.0,0,7.798,1,0,3327.00,3,0,NaN
6381138,a0f91e35f8458f,149a506a64c2b1,3a2cf335bc302f,1,2,138.60,0,0,12,25,...,1,0.0,0,0.000,0,0,1893.00,4,0,NaN
6381139,3696fc9f3a42b2,c770d7feaf020f,9d4e2b6d506fd0,0,0,19.80,0,0,0,86,...,0,0.0,0,0.000,0,0,68.89,0,1551,NaN

In [6]:
all_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6381140 entries, 0 to 6381139
Data columns (total 29 columns):
Id                 object
groupId            object
matchId            object
assists            int64
boosts             int64
damageDealt        float64
DBNOs              int64
headshotKills      int64
heals              int64
killPlace          int64
killPoints         int64
kills              int64
killStreaks        int64
longestKill        float64
matchDuration      int64
matchType          object
maxPlace           int64
numGroups          int64
rankPoints         int64
revives            int64
rideDistance       float64
roadKills          int64
swimDistance       float64
teamKills          int64
vehicleDestroys    int64
walkDistance       float64
weaponsAcquired    int64
winPoints          int64
winPlacePerc       float64
dtypes: float64(6), int64(19), object(4)
memory usage: 1.4+ GB

In [7]:
all_df['group_people_num']=all_df.groupby('groupId').Id.transform('count')

In [8]:
all_df['machId_num'] = all_df.groupby('matchId').Id.transform('count')

In [9]:
all_df.damageDealt = all_df.damageDealt.clip(0, all_df.damageDealt.quantile(q=0.8))

In [10]:
all_df.killPlace.replace(101, 100, inplace=True)

In [11]:
all_df.loc[(all_df.rankPoints!=-1) & (all_df.killPoints==0), 'killPoints'] = np.nan

In [12]:
all_df.killPoints.fillna(all_df.killPoints.mode()[0], inplace=True)

In [13]:
all_df.longestKill = all_df.longestKill.clip(0, all_df.longestKill.quantile(q=0.8))

In [14]:
from sklearn.preprocessing import StandardScaler

In [15]:
stds = StandardScaler()

In [16]:
train_df_matchDuration = stds.fit_transform(train_df.matchDuration.values.reshape(-1,1))

In [17]:
test_df_matchDuration = stds.transform(test_df.matchDuration.values.reshape(-1,1))

In [18]:
all_df.matchDuration = np.vstack([train_df_matchDuration, test_df_matchDuration])

In [19]:
dummies = ['matchType']

In [20]:
all_df['different'] = 0

In [21]:
all_df.loc[all_df.maxPlace!=all_df.numGroups, 'different'] = 1

In [22]:
train_df_rideDistance = stds.fit_transform(train_df.rideDistance.values.reshape(-1,1))
test_df_rideDistance = stds.transform(test_df.rideDistance.values.reshape(-1,1))
all_df.rideDistance = np.vstack([train_df_rideDistance, test_df_rideDistance])

In [23]:
train_df_swimDistance = stds.fit_transform(train_df.swimDistance.values.reshape(-1,1))
test_df_swimDistance = stds.transform(test_df.swimDistance.values.reshape(-1,1))
all_df.swimDistance = np.vstack([train_df_swimDistance, test_df_swimDistance])

In [24]:
train_df_walkDistance = stds.fit_transform(train_df.walkDistance.values.reshape(-1,1))
test_df_walkDistance = stds.transform(test_df.walkDistance.values.reshape(-1,1))
all_df.walkDistance = np.vstack([train_df_walkDistance, test_df_walkDistance])

In [25]:
all_df.loc[(all_df.rankPoints!=-1) & (all_df.winPoints==0), 'winPoints'] = np.nan
all_df.winPoints.fillna(all_df.winPoints.mode()[0], inplace=True)

In [26]:
all_df.loc[all_df.rankPoints==-1, 'rankPoints'] = np.nan
all_df.rankPoints.fillna(all_df.rankPoints.mode()[0], inplace=True)

In [27]:
all_df = pd.get_dummies(all_df, columns=dummies)

In [28]:
all_df.drop(['Id','groupId', 'matchId'], axis=1, inplace=True)

In [29]:
train = all_df[:train_n]
test = all_df[train_n:]
train.dropna(inplace=True)
train_y = train['winPlacePerc']
train = train.drop('winPlacePerc', axis=1)
test = test.drop('winPlacePerc', axis=1)

e:\å·¥å…·\python\python36\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [30]:
from sklearn.linear_model import Ridge
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor

In [31]:
X_train, X_test, y_train, y_test = train_test_split(train, train_y, random_state=42)
rd = Ridge()
rd.fit(X_train, y_train)

Ridge(alpha=1.0, copy_X=True, fit_intercept=True, max_iter=None,
      normalize=False, random_state=None, solver='auto', tol=0.001)

In [32]:
rd.score(X_test, y_test)

0.8480466865569276